import Header from "@/components/Header";
import ShowcaseCard from "@/components/ShowcaseCard";
import Showcaseheading from "@/components/Showcaseheading";
import ShowcaseSearch from "@/components/ShowcaseSearch";

const page = () => {
  const cardContent = [
    {
      img: "/image",
      heading: "Viasocket",
      text: "Each character is entirely unique and is generated by combining attributes such as colour palettes, skin tones, facial traits, outfits and accessories. With nearly endless combinations, all characters are guaranteed to be one of a kind.",
    },
    {
      img: "/image",
      heading: "Viaocket",
      text: "Each character is entirely unique and is generated by combining attributes such as colour palettes, skin tones, facial traits, outfits and accessories. With nearly endless combinations, all characters are guaranteed to be one of a kind.",
    },
  ];

  return (
    <div className="bg-black h-full w-full text-white">
      <div className="hero-bg">
        <Header />
        <Showcaseheading />
      </div>
      <ShowcaseSearch />
      <div className="grid grid-cols-2 w-3/4 mx-auto mt-20 gap-10 text-black pb-10">
        {cardContent.map((card, index) => (
          <ShowcaseCard
            key={index}
            img={card.img}
            heading={card.heading}
            text={card.text}
          />
        ))}
      </div>
    </div>
  );
};

export default page;
