import { Syne } from "next/font/google";


import "./globals.css";
import Wrapper from "@/wrapper/Wrapper";
import Navbar from "@/components/navbar";

const inter = Syne({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="dark">

      <body suppressHydrationWarning>
        <Wrapper>
          <Navbar />
          {children}
        </Wrapper>

      </body>
    </html>
  );
}


// "use client"


// import { useEffect } from "react";
// import Head from "next/head";
// import Wrapper from "@/wrapper/Wrapper";
// import Navbar from "@/components/navbar";

// // export const metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// export default function RootLayout({ children }) {
//   useEffect(() => {
//     // Function to initialize verification
//     const initVerification = (config) => {
//       // Code to initialize verification
//       // This function is called when the script is loaded
//     };

//     // Configuration object for the script
//     const configuration = {
//       referenceId: '870623l170791725365ccbfc587143',
//       success: (data) => {
//         // Handle success response
//         console.log('success response', data);
//       },
//       failure: (error) => {
//         // Handle failure reason
//         console.log('failure reason', error);
//       },
//     };

//     // Call the initVerification function with the configuration
//     initVerification(configuration);
//   }, []); // Empty dependency array ensures that the effect runs only once

//   return (
//     <div>
//       <Head>
//         <script
//           type="text/javascript"
//           dangerouslySetInnerHTML={{
//             __html: `
//               var configuration = {
//                 referenceId: '870623l170791725365ccbfc587143',
//                 success: (data) => {
//                   // Handle success response
//                   console.log('success response', data);
//                 },
//                 failure: (error) => {
//                   // Handle failure reason
//                   console.log('failure reason', error);
//                 },
//               };
//               function initVerification(config) {
//                 // Code to initialize verification
//               }
//               initVerification(configuration);
//             `
//           }}
//         />
//         <script
//           type="text/javascript"
//           src="https://proxy.msg91.com/assets/proxy-auth/proxy-auth.js"
//           onLoad="initVerification(configuration)"
//         />
//       </Head>
//       <Wrapper>
//         <Navbar />
//         {children}
//       </Wrapper>
//     </div>
//   );
// }
