import { Syne } from "next/font/google";


import "./globals.css";
import Wrapper from "@/wrapper/Wrapper";
import Navbar from "@/components/navbar";

const inter = Syne({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="wireframe">
      <body suppressHydrationWarning>
        <Wrapper>
          <Navbar />
          {children}
          </Wrapper>
       
        </body>
    </html>
  );
}
